######################################################################
# Automatically generated by qmake (3.0) Mie apr. 18 17:53:56 2018
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += Sudoku_lib/Board.h \
           Sudoku_lib/Cell.h \
           Sudoku_lib/Group.h \
           Sudoku_lib/Sudoku.h \
           Sudoku_lib/win_window.h
SOURCES += test.cpp \
           Sudoku_lib/Board.cpp \
           Sudoku_lib/Cell.cpp \
           Sudoku_lib/Group.cpp \
           Sudoku_lib/Sudoku.cpp \
           Sudoku_lib/win_window.cpp
QT += widgets
CONFIG += c++11
