######################################################################
# Automatically generated by qmake (3.0) Dum mar. 11 20:20:42 2018
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += Sudoku_lib/Board.h \
           Sudoku_lib/Cell.h \
           Sudoku_lib/Group.h \
           Sudoku_lib/Sudoku.h
SOURCES += test.cpp \
           Sudoku_lib/Board.cpp \
           Sudoku_lib/Cell.cpp \
           Sudoku_lib/Group.cpp \
           Sudoku_lib/Sudoku.cpp

QT += widgets
